"""ifc-console: a terminal interface to connect IFC files to LLMs."""

from typing import TYPE_CHECKING, Any

__version__ = "0.1.4"

# The SDK pulls in the whole backend, so it stays behind a lazy attribute:
# `ifc-console --help` must not pay for ifcopenshell.
__all__ = [
    "AsyncWorkbench",
    "Approval",
    "ApprovalRecord",
    "Authority",
    "ArtifactGCPlan",
    "ArtifactGCResult",
    "ArtifactRef",
    "AuditVerification",
    "BatchChildRecord",
    "BatchRecord",
    "BatchSpec",
    "BatchState",
    "Capability",
    "CapabilityDecision",
    "ChangeSet",
    "ChangeSetRecord",
    "ClassificationAssignmentChange",
    "CommitJobSpec",
    "CommitRecord",
    "CommitResult",
    "Envelope",
    "ErrorInfo",
    "IfcConsoleError",
    "IfcScalar",
    "JobEvent",
    "JobFailure",
    "JobRecord",
    "JobState",
    "ModelContext",
    "OperationAnnotations",
    "OperationContext",
    "OperationDefinition",
    "OperationPlugin",
    "PluginAPI",
    "PluginManifest",
    "PluginRecord",
    "PropertyCreateChange",
    "PropertyValueChange",
    "QueryBatchOperation",
    "QueryElementsData",
    "QueryJobSpec",
    "RestoreJobSpec",
    "RestoreRecord",
    "RestoreResult",
    "RevisionRef",
    "SourceFileRef",
    "TransactionJournal",
    "TransactionKind",
    "TransactionPhase",
    "ValidationBatchOperation",
    "ValidationData",
    "ValidationIssue",
    "ValidationJobSpec",
    "WorkflowInputSpec",
    "WorkflowPlan",
    "WorkflowQueryOperation",
    "WorkflowRecord",
    "WorkflowSpec",
    "WorkflowState",
    "WorkflowStepPlan",
    "WorkflowStepRecord",
    "WorkflowStepSpec",
    "WorkflowStepState",
    "WorkflowValidationOperation",
    "Workbench",
    "WorkspaceContext",
    "__version__",
]

if TYPE_CHECKING:
    from ifc_console.sdk import (
        Approval,
        ApprovalRecord,
        ArtifactGCPlan,
        ArtifactGCResult,
        ArtifactRef,
        AsyncWorkbench,
        AuditVerification,
        Authority,
        BatchChildRecord,
        BatchRecord,
        BatchSpec,
        BatchState,
        Capability,
        CapabilityDecision,
        ChangeSet,
        ChangeSetRecord,
        ClassificationAssignmentChange,
        CommitJobSpec,
        CommitRecord,
        CommitResult,
        Envelope,
        ErrorInfo,
        IfcConsoleError,
        IfcScalar,
        JobEvent,
        JobFailure,
        JobRecord,
        JobState,
        ModelContext,
        OperationAnnotations,
        OperationContext,
        OperationDefinition,
        OperationPlugin,
        PluginAPI,
        PluginManifest,
        PluginRecord,
        PropertyCreateChange,
        PropertyValueChange,
        QueryBatchOperation,
        QueryElementsData,
        QueryJobSpec,
        RestoreJobSpec,
        RestoreRecord,
        RestoreResult,
        RevisionRef,
        SourceFileRef,
        TransactionJournal,
        TransactionKind,
        TransactionPhase,
        ValidationBatchOperation,
        ValidationData,
        ValidationIssue,
        ValidationJobSpec,
        Workbench,
        WorkflowInputSpec,
        WorkflowPlan,
        WorkflowQueryOperation,
        WorkflowRecord,
        WorkflowSpec,
        WorkflowState,
        WorkflowStepPlan,
        WorkflowStepRecord,
        WorkflowStepSpec,
        WorkflowStepState,
        WorkflowValidationOperation,
        WorkspaceContext,
    )


def __getattr__(name: str) -> Any:
    if name in __all__ and name != "__version__":
        from ifc_console import sdk

        return getattr(sdk, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(__all__)
