"""Build a throwaway demo project so the panel has something real to work on.

A blank console is why a UI check turns into "open five tabs and click". The
scenario writes one IFC, one PDF manual, one reference image, and one
measurement recipe into a directory, so every agent surface (documents,
vision, measurements, proposals) has evidence the moment the panel opens.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

MANUAL_NAME = "Demo-Measurement-Manual.pdf"
IMAGE_NAME = "Demo-Wall-Detail.png"
RECIPE_NAME = "walls.yaml"
MODEL_NAME = "demo-building.ifc"

MANUAL_PAGES = (
    (
        "Demo Measurement Manual",
        [
            "Section 1. Scope",
            "",
            "This manual is generated by ifc-console for rehearsal runs.",
            "It is not a real specification and carries no engineering authority.",
            "",
            "Section 2. Wall thickness",
            "",
            "Measure interior walls across their structural layers only.",
            "Exclude any finish or render layer from the reported thickness.",
            "Report the value in millimetres with a tolerance of 2 mm.",
        ],
    ),
    (
        "Section 3. Complex geometry",
        [
            "Walls with curved or chamfered edges are measured on the local",
            "y extent of the solid, taken at mid height.",
            "",
            "Record the method used next to every value so a reviewer can",
            "reproduce it. A photograph without a scale bar is evidence of",
            "condition, never a source of dimensions.",
            "",
            "Section 4. Reporting",
            "",
            "Every reported value carries: metric, value, unit, method, source.",
        ],
    ),
)

RECIPE_YAML = """# Generated by `ifc-console dev`. Rehearsal data, not a specification.
- applies_to: {class: IfcWall}
  property: thickness
  method: geometry_extent
  params: {axis: local_y}
  unit: mm
  tolerance: 2
  source: {document: "Demo-Measurement-Manual.pdf", page: 2}
  notes: local y extent at mid height, per section 3
"""


@dataclass(frozen=True)
class Scenario:
    """Where the generated demo project and its pieces landed."""

    project_dir: Path
    model: Path
    references: tuple[Path, ...]
    recipe: Path | None
    notes: tuple[str, ...] = ()


def _write_manual(target: Path) -> bool:
    try:
        import pymupdf
    except ImportError:
        return False
    document = pymupdf.open()
    for heading, lines in MANUAL_PAGES:
        page = document.new_page()
        page.insert_text((72, 90), heading, fontsize=16)
        for index, line in enumerate(lines):
            page.insert_text((72, 130 + index * 18), line, fontsize=10)
    document.save(str(target))
    document.close()
    return True


def _write_detail_image(target: Path) -> bool:
    """A small labelled PNG so the vision paths have a real image to read."""
    try:
        import pymupdf
    except ImportError:
        return False
    document = pymupdf.open()
    page = document.new_page(width=520, height=320)
    page.draw_rect(pymupdf.Rect(60, 70, 460, 130), color=(0.1, 0.1, 0.1), width=1.5)
    page.draw_rect(pymupdf.Rect(60, 130, 460, 150), color=(0.4, 0.4, 0.4), width=1)
    page.insert_text((60, 55), "Wall detail (rehearsal drawing, no scale bar)", fontsize=11)
    page.insert_text((70, 105), "structural layer", fontsize=9)
    page.insert_text((70, 145), "finish layer, excluded", fontsize=9)
    page.insert_text((60, 200), "Thickness spans the structural layer only.", fontsize=9)
    pixmap = page.get_pixmap(dpi=110)
    pixmap.save(str(target))
    document.close()
    return True


def _build_model(target: Path) -> Path:
    import ifcopenshell
    import ifcopenshell.api.aggregate
    import ifcopenshell.api.context
    import ifcopenshell.api.geometry
    import ifcopenshell.api.project
    import ifcopenshell.api.pset
    import ifcopenshell.api.root
    import ifcopenshell.api.spatial
    import ifcopenshell.api.unit
    import numpy as np

    ifc = ifcopenshell.api.project.create_file(version="IFC4")
    project = ifcopenshell.api.root.create_entity(ifc, ifc_class="IfcProject", name="Rehearsal")
    lengths = ifcopenshell.api.unit.add_si_unit(ifc, unit_type="LENGTHUNIT")
    areas = ifcopenshell.api.unit.add_si_unit(ifc, unit_type="AREAUNIT")
    volumes = ifcopenshell.api.unit.add_si_unit(ifc, unit_type="VOLUMEUNIT")
    ifcopenshell.api.unit.assign_unit(ifc, units=[lengths, areas, volumes])
    model_context = ifcopenshell.api.context.add_context(ifc, context_type="Model")
    body = ifcopenshell.api.context.add_context(
        ifc,
        context_type="Model",
        context_identifier="Body",
        target_view="MODEL_VIEW",
        parent=model_context,
    )
    site = ifcopenshell.api.root.create_entity(ifc, ifc_class="IfcSite", name="Site")
    building = ifcopenshell.api.root.create_entity(
        ifc, ifc_class="IfcBuilding", name="Rehearsal Building"
    )
    storey = ifcopenshell.api.root.create_entity(
        ifc, ifc_class="IfcBuildingStorey", name="Level 1"
    )
    ifcopenshell.api.aggregate.assign_object(ifc, products=[site], relating_object=project)
    ifcopenshell.api.aggregate.assign_object(ifc, products=[building], relating_object=site)
    ifcopenshell.api.aggregate.assign_object(ifc, products=[storey], relating_object=building)

    layout = [
        (5.0, 0.24, "Interior Wall A", False),
        (4.0, 0.30, "Interior Wall B", False),
        (6.0, 0.40, "Exterior Wall C", True),
    ]
    for index, (length, thickness, name, external) in enumerate(layout):
        wall = ifcopenshell.api.root.create_entity(ifc, ifc_class="IfcWall", name=name)
        representation = ifcopenshell.api.geometry.add_wall_representation(
            ifc, context=body, length=length, height=3.0, thickness=thickness
        )
        ifcopenshell.api.geometry.assign_representation(
            ifc, product=wall, representation=representation
        )
        matrix = np.eye(4)
        matrix[1][3] = index * 2.0
        ifcopenshell.api.geometry.edit_object_placement(ifc, product=wall, matrix=matrix)
        ifcopenshell.api.spatial.assign_container(ifc, products=[wall], relating_structure=storey)
        pset = ifcopenshell.api.pset.add_pset(ifc, product=wall, name="Pset_WallCommon")
        ifcopenshell.api.pset.edit_pset(
            ifc,
            pset=pset,
            properties={"IsExternal": external, "FireRating": "F30" if index else "F90"},
        )
    ifc.write(str(target))
    return target


def build_scenario(project_dir: str | Path, *, model: str | Path | None = None) -> Scenario:
    """Create (or refresh) the demo project and return what it contains."""
    root = Path(project_dir).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    notes: list[str] = []

    target_model = root / MODEL_NAME
    if model is not None:
        source = Path(model).expanduser().resolve()
        if source != target_model:
            shutil.copy2(source, target_model)
    elif not target_model.exists():
        _build_model(target_model)

    references_dir = root / ".ifc-console" / "agents" / "references"
    references_dir.mkdir(parents=True, exist_ok=True)
    references: list[Path] = []
    manual = references_dir / MANUAL_NAME
    if manual.exists() or _write_manual(manual):
        references.append(manual)
    else:
        notes.append("PyMuPDF is missing, so no demo PDF or image was written")
    image = references_dir / IMAGE_NAME
    if image.exists() or _write_detail_image(image):
        references.append(image)

    from ifc_console.knowledge.project_recipes import recipes_dir

    recipe_dir = recipes_dir(root)
    recipe_dir.mkdir(parents=True, exist_ok=True)
    recipe = recipe_dir / RECIPE_NAME
    if not recipe.exists():
        recipe.write_text(RECIPE_YAML, encoding="utf-8")

    return Scenario(
        project_dir=root,
        model=target_model,
        references=tuple(references),
        recipe=recipe,
        notes=tuple(notes),
    )


__all__ = [
    "IMAGE_NAME",
    "MANUAL_NAME",
    "MODEL_NAME",
    "RECIPE_NAME",
    "RECIPE_YAML",
    "Scenario",
    "build_scenario",
]
